[package]
name = "hdwallet"
version = "0.2.2"
authors = ["jjy <jjyruby@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/jjyr/hdwallet"
keywords = [ "hdwallet", "BIP32", "wallet", "bitcoin", "crypto" ]
readme = "README.md"
description = "Hierarchical deterministic wallet (BIP-32)"

[workspace]
members = [
  "hdwallet-bitcoin"
]

[dependencies]
secp256k1 = "0.12"
rand = "0.6.1"
ring = "0.14.0"
lazy_static = "1.2.0"

[dev-dependencies]
hex = "0.3.2"
base58 = "0.1.0"
ripemd160 = "0.8.0"

